### ISSUE TITLE
`Manual Update Memo` の `Update Memo` stepでErrorが発生する。

### ISSUE THREAD

**Issue by m-Suda** [azu/hubmemo#2]
azuさんこんにちは。
素晴らしいシステムをありがとうございます。

今回こちらのテンプレートから作成したところ、タイトルのエラーが発生しました。
【エラー内容】
<img width="1439" alt="MemoHub_update-memo-error" src="https://user-images.githubusercontent.com/40332019/129227584-7fb74a1f-49a4-4811-8b7f-b75bf0a6ef31.png">

【再現手順】
[UsageのVia GUI](https://github.com/azu/hubmemo/blob/main/guide/USAGE.md#via-gui) 
※手順3.で発生します。

【修正方法】
`.github/workflows/manual-update-memo.yml` の 35行目、
```
run: yarn install && yarn ts-node-transpile-only index-manul.ts
```
を
```
run: yarn install && yarn ts-node-transpile-only index-manual.ts
```
に修正する。

**Comment by m-Suda** [comment]
こちら修正のプルリクエストになります。
お手すきの際にご確認よろしくお願いします。
[Update Memo stepのyarnコマンドにてファイル名にaが抜けていたため修正](https://github.com/azu/hubmemo/pull/4)

**Comment by azu** [comment]
closed by #4
